name: Feature Request
description: Suggest a new feature or enhancement for the Laravel Arc package.
title: "[Feature] "
labels:
  - type:feature
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 New Feature Suggestion

        Thank you for suggesting a new feature! Please describe it as clearly as possible so we can evaluate it properly.

  - type: input
    id: summary
    attributes:
      label: What is the feature?
      description: A short description of the proposed feature.
      placeholder: e.g. Add support for "boolean" fields in DTO generation
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature useful?
      description: Describe the problem this feature would solve.
      placeholder: |
        e.g. We need to define boolean flags in YAML like `is_active` and generate default values accordingly.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: How should it be implemented?
      description: Give technical hints on how it could be built (optional).
      placeholder: |
        e.g. Create `BooleanFieldGenerator` class that implements `FieldGeneratorInterface`.
    validations:
      required: false

  - type: textarea
    id: yaml-example
    attributes:
      label: YAML Example (optional)
      description: Provide an example of how the YAML config would look with this feature.
      placeholder: |
        fields:
          is_active:
            type: boolean
            default: true
    validations:
      required: false

  - type: input
    id: related-issues
    attributes:
      label: Related issues or PRs
      description: Link any related issues or pull requests.
      placeholder: e.g. #17, #42
    validations:
      required: false
