# Product DTO with modern trait-based system
header:
  dto: ProductDTO
  table: products
  model: App\Models\Product
  namespace: App\DTOs
  traits:
    - HasTimestamps
    - HasUuid
    - HasSoftDeletes
    - HasVersioning
  use:
    - App\Traits\Sluggable
  extends: BaseDTO

fields:
  name:
    type: string
    required: true
    validation: [required, string, min:2, max:255]
    transformers: [trim, title_case]
  
  description:
    type: text
    required: false
    validation: [nullable, string, max:1000]
    transformers: [trim]
  
  price:
    type: decimal
    required: true
    validation: [required, numeric, min:0]
  
  stock_quantity:
    type: integer
    default: 0
    validation: [integer, min:0]
  
  is_active:
    type: boolean
    default: true
    validation: [boolean]
  
  status:
    type: enum
    values: [draft, published, archived]
    default: draft
    validation: [required, in:draft,published,archived]
  
  tags:
    type: array
    required: false
    validation: [nullable, array, distinct]
  
  specifications:
    type: json
    required: false
    validation: [nullable, json]
  
  published_at:
    type: datetime
    required: false
    validation: [nullable, date]

relations:
  category:
    type: belongsTo
    target: App\Models\Category
  
  reviews:
    type: hasMany
    target: App\Models\Review

# Behavioral traits automatically add fields:
# - HasTimestamps: created_at, updated_at
# - HasUuid: id (UUID type)
# - HasSoftDeletes: deleted_at
# - HasVersioning: version